const constants = {
  GET_CATEGORIES: "GET_CATEGORIES",
  CATEGORIES_ERROR: "CATEGORY_ERROR",
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCT: "GET_PRODUCT",
  PRODUCT_ERROR: "PRODUCT_ERROR",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  PLACE_ORDER: "PLACE_ORDER",
};
export default constants;
